services:
  youtube-dl:
    image: ghcr.io/3n8/yt-dlp-server:latest
    hostname: youtube-dl-server.docker
    container_name: yt-dlp-server
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    networks:
      - frontend
    ports:
      - ${HOST_IP}:8085:8080
    cpus: 8
    mem_limit: 4G
    environment:
      - TZ=${TZ}
      - DOWNLOADS=/downloads
    volumes:
      - ${DOCKER_HOME}/youtube-dl:/config
      - /mnt/mergerfs/media/youtube-dl:/downloads
    dns:
      - ${DNS1}
      - ${DNS2}

networks:
  frontend:
    external: true
